{
  "PublicFilesDir": "/gpfs01/zhq_work/yn/PUBLIC_FILES/LAMMPS/",
  "mol_ratio": [
    {
      "DME": 1.4,
      "LiFSI": 1
    },
	{
      "DME": 3.8,
      "LiFSI": 1
    }
  ],
  "expand_factor": [
    200,
    200
  ],
  "parallel_run": 2,
  "temperature": [
    298.15,
    450.15
  ],
  "runtime":[
    2000000,
    500000,
    1000000,
    500000,
    4000000,
    2000000,
    5000000
  ],
  "compute_type": false
}
